'use server';

import { getFirebase } from "@/lib/firebase/config";
import { doc, setDoc, Timestamp, addDoc, collection, deleteDoc } from "firebase/firestore";
import { revalidatePath } from "next/cache";

interface PageData {
    slug: string;
    title: string;
    content: string;
    category: string;
    order: number;
    isActive: boolean;
    inFooter: boolean;
}

export async function createPageAction(data: PageData) {
    const { db } = getFirebase();
    
    // The document ID will be auto-generated by Firestore
    const pageRef = doc(collection(db, "websitePages"));
    
    await setDoc(pageRef, {
        ...data,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now()
    });

    revalidatePath('/'); // Revalidate home to update footer
    revalidatePath(`/${data.slug}`); // Revalidate the specific page
}


export async function updatePageAction(id: string, data: Partial<PageData>) {
    const { db } = getFirebase();
    const pageRef = doc(db, "websitePages", id);
    
    await setDoc(pageRef, { 
        ...data,
        updatedAt: Timestamp.now()
    }, { merge: true });

    revalidatePath('/'); // Revalidate home page to update footer
    if (data.slug) {
     revalidatePath(`/${data.slug}`); // Revalidate the specific page path
    }
}

export async function deletePageAction(id: string) {
    const { db } = getFirebase();
    const pageRef = doc(db, "websitePages", id);

    await deleteDoc(pageRef);

    revalidatePath('/'); // Revalidate home page to update footer
    // We don't need to revalidate the slug path as it will be gone
}
